global:
  postgresql:
    auth:
      postgresPassword: "${POSTGRES_PASSWORD}"
      username: "${POSTGRES_USER}"
      password: "${POSTGRES_PASSWORD}"
      database: "backstage"
primary:
  name: primary
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  persistence:
    enabled: true
    size: 8Gi